spring.application.name=rework

# Supabase PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.lokiktkwuujhfohyoody
spring.datasource.password=99EzBzMRoV38PrRz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS Configuration
aws.access.key.id=${AWS_ACCESS_KEY_ID:}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY:}
aws.region=ap-southeast-2
cognito.user.pool.id=ap-southeast-2_p7mounHZf
